src/pages/index.tsx, src/services/api/auth/index.ts
=> [#12][FEATURE] 공통_로그인 뷰 퍼블리싱

src/services/api/auth/index.ts
=> fix: login error

src/utils/index.ts
=> fix: precision error

src/components/attendanceAdmin/session/CreateSessionModal/style.ts, src/components/common/modal/style.ts, src/utils/zIndex.ts
=> Hotfix 230421

src/components/attendanceAdmin/session/CreateSessionModal/index.tsx, src/components/attendanceAdmin/session/CreateSessionModal/style.ts
=> fix : 디자인 QA - 출석생성 모달 값 유무에 따른 border 색상 변경

src/components/attendanceAdmin/session/CreateSessionModal/index.tsx, src/components/common/DropDown/style.ts
=> Hotfix 230425

src/utils/session.ts
=> fix : ios req error

src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx, src/components/attendanceAdmin/totalScore/MemberDetail/style.ts, src/components/attendanceAdmin/totalScore/MemberList/index.tsx, src/data/sessionData.ts, src/pages/attendanceAdmin/session/[id].tsx, src/services/api/attendance/index.ts, src/services/api/lecture/index.ts, src/services/api/member/index.ts, src/types/global.d.ts
유저별 출석정보 상세페이지를 구현했습니당... 이걸 이제야 만드네요
- 출석정보 리스트가 스크롤이 되어야 하는데, 기존 table 로는 tbody만 스크롤이 되지 않아요. 그래서 table을 2개로 분리시켰어요!
- 기본 스크롤바때문에 테이블이 밀렸는데, 이거 작업하는 겸 약간의 커스텀을 했어요
- 모달 내부에서 스크롤이 가능하기 때문에 배경은 스크롤이 되지 않도록 만들었어요
- 겹치는 interface를 정리했어요
=> [#4][FEATURE] 출석총점_회원선택 모달 구현

package.json, src/components/attendanceAdmin/session/CreateSessionModal/index.tsx, src/components/attendanceAdmin/session/CreateSessionModal/style.ts, src/components/attendanceAdmin/session/SessionList/index.tsx, src/components/attendanceAdmin/session/SessionList/style.ts, src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx, src/components/attendanceAdmin/totalScore/MemberDetail/style.ts, src/components/attendanceAdmin/totalScore/MemberList/index.tsx, src/components/attendanceAdmin/totalScore/MemberList/style.ts, src/components/common/DropDown/style.ts, src/components/common/Nav/index.tsx, src/components/common/modal/index.tsx, src/components/common/modal/style.ts, src/components/session/Select/style.ts, src/data/sessionData.ts, src/pages/attendanceAdmin/session/[id].tsx
QA 시트에 있는 수정사항 반영
- 출석 드롭다운 수정
- 출석 종료 후 버튼 비활성화
- ... 처리 추가
그 외에 추가적인 수정사항
- Nav 상세페이지에서 focus 안 되는 오류 수정
- 애니메이션 추가
- input focus 변경
- radio label 클릭 가능하게 변경
=> fix: QA 수정사항 반영

src/utils/session.ts
세선 생성시 30분 단위의 시간을 선택할 수 있도록 했어요!
=> feat : 30분 단위 시간 추가

src/components/attendanceAdmin/session/CreateSessionModal/style.ts, src/components/common/DropDown/style.ts
6월 3일 디자인 QA 수정사항들을 반영했습니다.
1. 컬러 속성 세부지정
2. input outline 속성 적용
=> fix : 디자인 QA 수정

src/components/attendanceAdmin/session/SessionList/index.tsx, src/pages/attendanceAdmin/session/[id].tsx
2023년 6월 27일 디자인 QA 사항을 반영했습니다.
- 세션 리스트 -> 세션 상세로 이동하는 버튼 `관리` -> `조회` 로 변경
- 세션 상세 페이지 세션 제목 `<strong>`태그 `margin` `0.8rem` 적용
=> 230627 - 디자인 QA 사항 반영

src/components/attendanceAdmin/session/SessionList/index.tsx, src/services/api/lecture/index.ts
- 세션 삭제 API 를 연결했습니다.
- 연결 확인을 위해 임시 버튼을 구현하였습니다. 세션 디테일 모달이 완성되면 그때 프로덕션 배포를 진행하면 될 것 같습니다.
=> [#40][FEATURE]세션 삭제 API 연결

src/assets/icons/IcCheckBox.tsx, src/components/attendanceAdmin/session/SessionList/SessionDetailModal/index.tsx, src/components/attendanceAdmin/session/SessionList/SessionDetailModal/style.ts, src/components/attendanceAdmin/session/SessionList/index.tsx, src/components/attendanceAdmin/session/SessionList/style.ts, src/components/common/ListWrapper/style.ts, src/components/common/inputContainer/index.tsx, src/components/common/inputContainer/style.ts
- 세션 상세 조회 모달의 레이아웃을 구성 했습니다.
- 추후 세션 생성 모달의 `InputContainer` 를 추상화 하기 위한 공통 컴포넌트를 만들었습니다.
=> [#47][FEATURE]세션 상세 조회 레이아웃 구현

src/components/attendanceAdmin/session/SessionList/SessionDetailModal/index.tsx, src/components/attendanceAdmin/session/SessionList/index.tsx, src/components/common/inputContainer/style.ts, src/services/api/lecture/index.ts, src/types/global.d.ts
- 세션 상세 조회/삭제의 api 연결과 뷰 구성을 모두 마쳤습니다.
- 날짜, 시간에 대한 api 명세 방식에 대한 논의가 필요할 것 같아 명세서가 변경되면 수정이 필요할 것 같습니다!
=> [#50][FEATURE]세션 상세 조회/삭제 api 연결

package.json, src/components/attendanceAdmin/session/CreateSessionModal/index.tsx, src/components/attendanceAdmin/session/CreateSessionModal/style.ts, src/components/attendanceAdmin/session/SessionList/SessionDetailModal/index.tsx, src/components/attendanceAdmin/session/SessionList/index.tsx, src/components/common/DropDown/style.ts, src/components/common/inputContainer/index.tsx, src/components/common/inputContainer/style.ts, src/hooks/useDateFormat.ts, src/pages/attendanceAdmin/session/[id].tsx, src/types/global.d.ts, yarn.lock
- `InputContainer` 컴포넌트를 활용하여 `CreateSessionModal` 을 리팩토링 하였습니다.
- 코드 중복을 해결할 수 있는 방법이 있다면 알려주세요!
`SessionDetailModal` 과 `CreateSessionModal` 안에 들어가는 chiledren 이 달라서 적절하게 적용하는데 어려움이 있었습니다.
=> [#53][REFACTOR] inputContainer 추상화

src/components/common/DropDown/style.ts
`nav` 에서 기수선택 드롭다운이 노출되지 않는 문제를 수정했습니다.
=> fix : 드롭다운 위치 수정

src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
- createSession 날짜 포맷을 ISO 8601 형식으로 변경하여 세션생성이 되지 않는 문제는 해결했습니다.
=> [#63}[REFACTOR] createSession 날짜 포맷 ISO 8601 형식으로 변경

src/components/common/Nav/index.tsx
Nav 의 드롭다운의 외부를 클릭하면 드롭다운이 닫히도록 UX 를 개선했습니다.
=> refactor : 드롭다운 외부 클릭 시 닫힘

src/components/attendanceAdmin/session/SessionList/SessionDetailModal/index.tsx, src/components/attendanceAdmin/session/SessionList/index.tsx, src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx, src/components/attendanceAdmin/totalScore/MemberList/index.tsx, src/data/queryData.ts, src/hooks/useObserver.ts, src/pages/attendanceAdmin/session/[id].tsx, src/services/api/attendance/index.ts, src/services/api/attendance/query.ts, src/services/api/lecture/index.ts, src/services/api/lecture/query.ts, src/services/api/member/index.ts, src/services/api/member/query.ts, src/utils/index.ts
- API 분리 (index, query) 및 정리
- useQuery 적용
- useInfiniteQuery 적용 + useObserver hook 구현
- 컴포넌트 내에서 return 전에 분기처리가 있을 경우(ex. `if (!id) return null;`) useRef가 제대로 적용되지 않아요.
이는 useRef가 처음엔 null이다가 HTMLElement 값으로 변경되어도 리렌더링이 발생하지 않기 때문이죠. 따라서 useRef가 조건부 렌더링되지 않도록 해야해서 마음에 들지 않는 구조가 나왔어요.
- 지금 페이지네이션은 `?page=0` 방식으로만 되어있는데, 기존에 다른 프로젝트에서는 prev, next, cursor 가 존재해서 약간 헷갈렸습니당..
Closes #13
=> [#13][FEATURE] 공통_react query + 무한스크롤 적용

emotion.d.ts, src/components/common/HelperText/index.tsx, src/components/common/HelperText/style.ts, src/hooks/useObserver.ts, src/pages/attendanceAdmin/session/[id].tsx, src/styles/theme.ts, src/utils/zIndex.ts
HelperText를 구현했어요
HelperText 자체를 재사용할 수 있도록 `StWrapper` 를 props로 넘겨주는 방식으로 구현했어요
애니메이션 쫀득하게 만들기?
=> [FEATURE] helper text 추가

src/components/attendanceAdmin/session/AttendanceModal/index.tsx
=> fix: setInterval 오류 수정 및 조기종료 추가

package.json, src/components/attendanceAdmin/session/AttendanceModal/index.tsx, src/components/attendanceAdmin/session/SessionList/SessionDetailModal/index.tsx, src/components/attendanceAdmin/session/SessionListFooter/index.tsx, src/components/common/Nav/index.tsx, src/components/session/Select/index.tsx, src/hooks/useRecoilGenerationSSR.ts, src/pages/attendanceAdmin/session/[id].tsx, src/styles/global.ts, src/utils/date.ts, src/utils/generation.ts, yarn.lock
- 타이머 조기종료 로직
- 출석상태 변경 시 리스트가 바뀌는 오류 수정
- 이름(두 글자) 정렬 오류 수정
- mds 패키지 설치
=> [231026] dev -> main merge

src/components/alarmAdmin/AlarmList/index.tsx, src/components/alarmAdmin/AlarmList/style.ts, src/pages/alarmAdmin/index.tsx, src/pages/attendanceAdmin/session/[id].tsx, src/services/api/alarm/index.ts, src/services/api/alarm/query.ts, src/types/global.d.ts, src/utils/translator.ts
=> feat: 알림 관리 리스트 구현

src/components/alarmAdmin/CreateAlarmModal/index.tsx, src/components/common/Button/style.ts
=> [FIX] submit  버튼 활성화 문제 해결

src/components/attendanceAdmin/session/AttendanceModal/index.tsx, src/components/attendanceAdmin/session/AttendanceModal/style.ts
- `AttendanceModal` 컴포넌트를 mds 디자인에 맞춰 변경했습니다.
- 폰트가 mds에 없는게 존재해서 추후에 추가하거나, 여기서만 사용되는 특수한 폰트라면 그냥 둬도 될 것 같습니다!
=> [STYLE]1/2차 출석 모달 mds 형식에 맞춰 변경

src/components/org/OrgAdmin/RecruitSection/Fna.tsx, src/components/org/OrgAdmin/RecruitSection/Header.tsx, src/components/org/OrgAdmin/RecruitSection/PartCurriculum.tsx, src/components/org/OrgAdmin/RecruitSection/style.ts, src/components/org/OrgAdmin/assets/RequiredIcon.tsx
=> [FEATURE] 지원하기 탭 UI 수정

src/components/org/OrgAdmin/MyDropzone/index.tsx
=> [BUG] dropzone 클릭으로도 파일 입력가능하게 하기

src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx, src/components/org/OrgAdmin/PartCategory/index.tsx, src/components/org/OrgAdmin/RecruitSection/Fna.tsx, src/components/org/OrgAdmin/RecruitSection/PartCurriculum.tsx, src/components/org/OrgAdmin/RecruitSection/index.tsx, src/components/org/OrgAdmin/index.tsx, src/utils/org.ts
- 제출 시 에러 메세지 안 사라지는 에러 해결
- 파트별 소개, FNA 다 선택해야 폼 제출되도록 수정
- 반복되는 로직 제거
- 지원하기 탭 모든 값 입력 시 데이터 정상적으로 전송 확인
=> [FEATURE] 지원하기 탭 hook-form 고도화 

src/components/alarmAdmin/AlarmList/index.tsx, src/components/alarmAdmin/AlarmList/style.ts, src/components/alarmAdmin/ShowAlarmModal/index.tsx, src/components/alarmAdmin/ShowAlarmModal/style.ts, src/components/common/Header/style.ts, src/components/common/Nav/style.ts, src/components/common/modal/ModalHeader/style.ts, src/pages/alarmAdmin/index.tsx, src/services/api/alarm/index.ts, src/services/api/alarm/query.ts, src/types/global.d.ts, src/utils/alarm.ts, src/utils/translator.ts
- 알림 조회 리스트 수정
- 알림 조회 상세 일부 구현
- mds 적용
- 바뀐 API 스펙 적용
- 추가사항 : 웹링크/딥링크일 경우, 알림 상세 조회에 링크 추가
=> [FEATURE] 알림 리스트 & 상세 조회

src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx
label 맞도록 수정했어요
https://github.com/user-attachments/assets/64337e6f-518d-4d06-ade1-9fbcc0e1d7b1
=> [BUG] 소개 탭 파트별 커리큘럼 label 미스 매치

src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx, src/components/org/OrgAdmin/AboutSection/Executives/ExecInfo.tsx, src/components/org/OrgAdmin/MyDropzone/index.tsx
=> [FEATURE] 에러 상태 빠진 곳 UI 구현

src/components/org/OrgAdmin/api.ts, src/components/org/OrgAdmin/index.tsx
배포 mutate 연결해서 배포 성공하는것까지 확인
- Dto에 맞게 Transform, 만들어준 requestBody 넣어서 sendData 연결
- **에러1)** baseURL이 잡히지 않는 문제가 있었음 
- baseURL config에서 가져오도록 수정해서 해결 
- **에러2)** presignedURL api가 모두 실패했었음
- POST method -> PUT method로 수정해서 해결 
마지막에 쏘는 API다 정상 작동하는거 확인했습니다
=> [FEATURE] org admin 배포 연결

src/components/org/OrgAdmin/CommonSection/style.ts
=> [CHORE] text style 변경

src/components/common/Nav/index.tsx
=> [Feat] 배너 어드민 권한 추가

src/pages/index.tsx
=> [FIX] 메이커스 계정 리다이렉트 url 수정

src/components/alarmAdmin/AlarmList/index.tsx, src/components/alarmAdmin/CreateAlarmModal/index.tsx, src/components/alarmAdmin/CreateAlarmModal/type.ts, src/components/alarmAdmin/CreateAlarmModal/utils.ts, src/components/alarmAdmin/ShowAlarmModal/index.tsx, src/services/api/alarm/index.ts, src/types/global.d.ts
=> [알림 어드민] high priority QA 사항 해결

src/components/alarmAdmin/AlarmList/index.tsx, src/types/global.d.ts
=> [알림 어드민] 필드명 오타 수정 및 알림 리스트 아이템 시간 intentAt 으로 수정

src/components/alarmAdmin/AlarmList/index.tsx, src/components/alarmAdmin/CreateAlarmModal/index.tsx, src/components/alarmAdmin/CreateAlarmModal/type.ts, src/components/alarmAdmin/CreateAlarmModal/utils.ts, src/components/alarmAdmin/ShowAlarmModal/index.tsx, src/services/api/alarm/index.ts, src/types/global.d.ts
* fix: 알림 발송 throttle
* fix: id prop 수정 및 삭제하기 refetch
* fix: send/intend time 분기
* fix: 지난 날짜 선택 안되도록
* feat: 딥링크 추가
* fix: 필드명 오타 수정 및 알림 리스트 아이템 시간 intentAt 으로 수정 (#234)
---------
=> Prod 배포 (#235)

src/components/common/Nav/index.tsx
=> [Feat] 메이커스 어드민 지원서 관리 메뉴 추가

src/components/alarmAdmin/ShowAlarmModal/index.tsx
target type 보여줄 수 있도록, 기존 매핑 객체 사용안하는 방향으로 수정
=> [HOTFIX] target type 보여줄 수 있도록, 기존 매핑 객체 사용안하는 방향으로 수정

src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx, src/components/attendanceAdmin/totalScore/MemberList/index.tsx, src/hooks/useObserver.ts, src/pages/attendanceAdmin/session/[id].tsx
- 인증중앙화를 하면서 없어진 속성 반영
- 무한 스크롤시 무한 요청이 가는 이슈 해결
=> Prod 배포 (인증 중앙화 관련 수정사항 반영)
