sopt-makers/sopt-operation-frontend

- src/components/common/Button/index.tsx
- src/components/common/Button/style.ts
- src/components/common/Footer/index.tsx
- src/components/common/Footer/style.ts
- src/components/common/ListWrapper/index.tsx
- src/components/common/ListWrapper/style.ts
- src/components/common/PartFilter/index.tsx
- src/components/common/PartFilter/style.ts
- src/data/sessionData.ts
- src/pages/attendanceAdmin/session/[id].tsx
- src/styles/global.ts
- src/utils/index.ts
- src/utils/translator.ts
공통으로 사용하는 ListWrapper, Button, Footer, PartFilter를 구현했어요
- 폰트 스타일이 아직 정리가 안 돼서 디자인 시스템과 다른 폰트는 직접 입력했어요. 정리가 끝나면 추후에 변경하도록 할게요
- ListWrapper는 리스트로 구현하면 굉장히 복잡해질 것 같아서 테이블로 구현했어요. 그래서 css가 조금 요상해보일지도? 테이블 css 커스텀이 생각보다 까다롭더라구요
- PartFilter에서 파트 리스트를 불러올 때 `Object.keys(partTranslator)` 를 사용하려다가, 이렇게 하면 `as`를 써야해서 `partList` 변수를 별도로 만들었어요
- Footer는 페이지에 따라 유무가 달라지므로 각 페이지에서 관리하도록 구현했어요. 이 과정에서 부득이하게 페이지 내에서 emotion을 사용해야하는데, 어떻게 관리하면 좋을까요? 피클은 Next가 아니라서 페이지 내에서 style 파일을 분리했더라구요.
- 더미데이터는 API 연결 후에 삭제 예정!
- 테이블 커스텀...
> [#2][FEATURE] 공통_공통 컴포넌트 구현

- src/components/attendanceAdmin/session/AttendanceModal/index.tsx
- src/components/attendanceAdmin/session/AttendanceModal/style.ts
- src/components/common/Button/index.tsx
- src/data/sessionData.ts
- src/pages/attendanceAdmin/session/[id].tsx
- src/services/api/lecture/index.ts
- src/types/global.d.ts
`N차 출석하기` 기능을 구현했습니다
- `AttendanceModal` 에서 타이머를 구현하기 위해 클로저를 사용했는데, `useState` 만 사용한다면 `setInterval` 내부에서 상태값이 의도한 대로 바뀌지 않기 때문이에요. 혹시 더 좋은 방법 있으면 제안해주세요!
- `next.config.js`의 `reactStrictMode` 옵션때문에 `useEffect` 가 2번씩 호출되는 케이스가 있어요. [관련 문서](https://react.dev/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development) 아직 기능상으로 문제가 되지는 않기 때문에 리팩토링 할 때 수정하는 걸로...
- `startAt` 의 타입이 `string | null` 인데, string 타입이면서 길이가 1 이상인지 판단하기 위해 `!!startAt` 을 사용했는데 다른 방법이 있을까요?
> [#22][FEATURE] 출석세션_출석하기

- src/components/common/FilterButton/index.tsx
- src/components/common/FilterButton/style.ts
- src/components/common/PartFilter/index.tsx
#24 
- 공홈 어드민에서 PartFilter 컴포넌트와 같이 ButtonGroup이 필요한 케이스가 생겼습니다.
-  하지만 PartList와 의존성이 강해서 분리를 하였습니다.
> [#24] [REFACTOR] PartFilter 의존성 분리

- src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
- src/components/attendanceAdmin/session/SessionList/index.tsx
- src/components/attendanceAdmin/totalScore/MemberList/index.tsx
- src/components/common/Nav/index.tsx
- src/hooks/useCreateSession.ts
- src/recoil/atom.ts
- 기수 선택 드롭다운 값에 따라 보여지는 정보가 달라지도록 리팩토링 하였습니다.
- 선택된 기수의 화면에서 세션 생성시 해당 기수에 맞는 리스트에 새션이 생성되도록 하였습니다.
각 함수가 받는 인자는 number, 드롭다운에서 인자로 받는 값은 string 인데, 이것을 변환하는데 `parseInt()` 를 사용했습니다.
이대로 두는게 좋을까요 드롭다운의 타입을 좀 더 유연하게 변경하는게 좋을까요?
타입 안정을 위해서는 이대로 두는게 더 좋을 것 같다고 생각하는데 어떻게 생각하시는지 궁급합니다!
https://github.com/sopt-makers/sopt-operation-frontend/assets/97586683/17896dc9-2f34-41bb-90a9-55b770a1060b
> [#44][REFACTOR] 기수 선택시 API 재호출

- src/components/attendanceAdmin/session/SessionList/index.tsx
- src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx
- src/pages/attendanceAdmin/session/[id].tsx
- 서버측에서 보내온 ISO 8601 형식의 날짜 표기 방식을 뷰에 맞게 포맷을 변경합니다.
- `dayjs` 를 사용해서 작업하였습니다.
- `useDateformat` 이라는 커스텀 훅을 만들어서 사용하려고 했으나 `map()` 메서드 안에서 훅을 사용하게 되면 eslint 에 걸리게 됩니다. 그래서 사용하는 곳이 한정적이게 되는데, 그냥 커스텀 훅을 사용하지 말지, 아니면 좀더 추상화를 할 수 있는 방법이 있는지 궁금합니다.
> [#54][REFACTOR] ISO 8601 형식 적용

- src/recoil/atom.ts
atom 의 default 값을 `33` 으로 수정하여 33기 정보가 우선적으로 노출되도록 했습니다.
> chore : recoil atom default 값 변경

- src/components/attendanceAdmin/session/CreateSessionModal/style.ts
- src/components/orgAdmin/TextField/style.ts
dev 에서 적용되지 않았던 보라색 걷어내기 작업 (DatePicker, 공홈 어드민) 부분에서의 보라색 컬러를 제거하였습니다.
> [#66][REFACTOR] 보라색 걷어내기 sprint0 ver.

- src/services/api/auth/index.ts
- src/services/api/client.ts
- 엑세스 토큰 만료시(`400`) 로그인 화면으로 리디렉션 되도록 하였습니다.
- 인터셉터의 재귀호출.. 꼭 막아야합니다..
> fix : 리프레시 토큰 요청에 대한 400 에러 리디렉션

- package.json
- src/components/attendanceAdmin/session/SessionList/index.tsx
- src/components/attendanceAdmin/session/SessionListFooter/index.tsx
- src/components/attendanceAdmin/totalScore/MemberList/index.tsx
- src/components/common/ListActionButton/index.tsx
- src/components/common/ListActionButton/style.ts
- src/components/common/ListWrapper/style.ts
- src/components/common/Nav/index.tsx
- src/components/session/Select/index.tsx
- src/hooks/useRecoilGenerationSSR.ts
- src/pages/attendanceAdmin/session/[id].tsx
- src/recoil/atom.ts
- yarn.lock
Closes #70 
- 현재 활동중인 기수를 제외한 나머지 기수에서 세션생성, 출석 개별갱신을 불가능하도록 설정했습니다.
- 출석 개별갱신 버튼이 `disabled` 일 경우 `display:none` 이 되는 것이 아닌 `disabled` 에 해당하는 스타일링이 적용되도록 변경했습니다.
- 세션목록, 세션상세, 출석총점 탭에서 공통적으로 사용되는 `관리`, `조회`, `갱신`  버튼을 `ListActionButton` 이라는 이름의 컴포넌트로 추상화하였습니다.
- Nav의 기수 드롭다운에서 결정되는 atom 값을 이용해 각 컴포넌트에서 기능 비활성화 여부를 결정했는데, 여러 컴포넌트에 useRecoilValue 의 사용과 조건을 넣어주는것이 번거로워 이 기수판별 로직을 담당하는 커스텀 훅을 만드는게 어떨까 고민중에 있습니다.
왜냐하면 나중에 34기로 기수를 변경한다고 치면 하드코딩된 부분을 모두 변경해줘야 하기때문에...
조건부.. 렌더링..
> [#70][REFACTOR] 이전 기수에 대한 세션 생성/출석 기능 제한

- src/components/attendanceAdmin/session/SessionList/SessionDetailModal/index.tsx
- src/components/attendanceAdmin/session/SessionListFooter/index.tsx
- src/components/common/Nav/index.tsx
- src/components/session/Select/index.tsx
- src/hooks/useRecoilGenerationSSR.ts
- src/pages/attendanceAdmin/session/[id].tsx
- src/utils/activityGeneration.ts
- src/utils/date.ts
- src/utils/generation.ts
Closes #75 
- 기존 recoil atom 값을 통해 관리되던 이전기수에 대한 비활성화 로직을 서버에서 받아온 값으로 처리하도록 변경했습니다.
- 각종 조건부 렌더링에 '33' 으로 하드코딩 되어있던 활동기수 값을 `activityGeneration` 이라는 값으로 저장하여 추후 관리하기 쉽도록 변경했습니다.
- hook 이 포함되어 있지 않았지만 hook 으로 분류되었던 `useDateFormat` 함수를 `transDate` 라는 일반함수로 변경하고 `utils/date` 디렉토리로 이동시켰습니다.
코드보고 혹시 아직 하드코딩 되어있는 부분 있으면 알려주세요..!!
> [#75][REFACTOR] 출석 관련 로직 비활성화, 서버측 데이터로 제어

- src/components/attendanceAdmin/session/SessionList/index.tsx
- src/components/attendanceAdmin/session/SessionList/style.ts
- 기존의 세션 상세 모달에서 진행하던 세션 삭제 작업을 리스트의 IcMore 를 클릭하면 작동할 수 있도록 작업했습니다.
- 기존의 세션 상세 모달은 일단 필요하지 않을 것으로 생각되는데, pm pd 와 논의가 필요할 것 같습니다.
> [REFACTOR] 세션 삭제 로직 변경

- src/components/attendanceAdmin/session/AttendanceModal/index.tsx
- src/pages/attendanceAdmin/session/[id].tsx
- src/services/api/lecture/query.ts
- [해당 이슈](https://sopt-makers.slack.com/archives/C06KS9ATSG1/p1724484388577249)의 문제를 해결하기 위해 출석 시작을 담당하는 useEffect에서 refetch를 유발하는 dependency인 finishAttendance를 제거합니다.
- 순수하게 모달을 닫는 함수를 전달할 수 있는 onClose prop을 생성합니다.
- 멤버, 세션 정보를 불러오는 Query의 refetchOnReconnect 옵션을 false 로 설정하여 네트워크 변동에 출석 모달이 영향받지 않도록 수정합니다.
- 해당 대응은 당장의 문제를 해결할 수 있지만, 최고의 해결책은 아니라고 생각합니다. 로직과 뷰를 분리하는 리팩토링이 필요해 보입니다.
https://github.com/user-attachments/assets/66445f2f-d51c-4043-95db-75c05144459c
https://github.com/user-attachments/assets/4294e5de-bfb6-4b63-93b3-bafcfc2a48f6
> [REFACTOR]: 순수 onClose prop 추가, session, member resetchOnReconnect 옵션 추가

- src/components/org/OrgAdmin/AboutSection/CoreValue/index.tsx
- src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx
- src/components/org/OrgAdmin/AboutSection/Executives/ExecInfo.tsx
- src/components/org/OrgAdmin/RecruitSection/Fna.tsx
- src/components/org/OrgAdmin/RecruitSection/PartCurriculum.tsx
소개탭에 required 조건 추가 및 error 처리를 추가해주었어요. 
그런데 errors 객체 사용하는 과정에서 제가 register label로 사용하던 방식(이전 PR 참고)이 타입에러를 발생시키더라구요. 
빨간줄을 해결하기 위해서는 제가 사용했던 API 스키마와 동일한 구조가 될 수 있도록 FormValue 타입을 따로 선언해줘야 하는 것으로 보였는데, 
현재는 그렇게 타입을 고도화할 시간이 없어서 일단 객체 구조였던 register label을 모두 flatten 시켜서 string화 해주었습니다. 
제 컨벤션을 적용시켰던 지원하기 탭에서도, 언석오빠가 최초에 작업해주었던 isError 및 errorMessage가 다 정상작동 하고 있지 않더라구요 
그래서 label 모두 flatten 시켜주고 errors 처리도 정상화시켜주었습니다. 
https://github.com/user-attachments/assets/3d7aa44c-a7ce-44e3-aeb2-bac8dd5d5262
> [FEATURE] 소개탭, 지원하기탭 필수조건 에러처리 및 label 수정

- src/components/org/OrgAdmin/CommonSection/BrandingColor.tsx
- src/components/org/OrgAdmin/CommonSection/BrandingSubColor.tsx
- src/components/org/OrgAdmin/CommonSection/ColorInputField.tsx
- src/components/org/OrgAdmin/CommonSection/GenerationInformation.tsx
- src/components/org/OrgAdmin/CommonSection/RecruitSchedule.tsx
- src/components/org/OrgAdmin/CommonSection/style.ts
- src/utils/org.ts
- closed #141 
- 앞선 PR에서 말씀드린 것처럼 form label flatten 작업 동일하게 해주었습니다 
- colorPicker과 date input 쪽에서 hook form을 활용해서 조건부 스타일링 / 조건부 렌더링되도록 로직 반영했습니다 
- OB/YB 칩 선택 시 컴포넌트가 새로이 렌더링되지 않아 key prop 추가하기 위해 div wrapper 추가해주었습니다
> [FEAUTRE] 공홈 어드민 공통 탭 hook form 연결

- src/components/org/OrgAdmin/CommonSection/BrandingSubColor.tsx
- src/components/org/OrgAdmin/CommonSection/RecruitSchedule.tsx
- src/components/org/OrgAdmin/CommonSection/index.tsx
- src/components/org/OrgAdmin/CommonSection/style.ts
- src/components/org/OrgAdmin/index.tsx
- src/components/org/OrgAdmin/types.ts
- src/utils/org.ts
- 서브 컬러 error 표시 안 되는 에러 해결
- 에러 메세지 표시될 때 color preview box 밑으로 내려가는 에러 해결
- ob / yb 둘 다 선택해야 폼 제출되도록 수정
- 모집 일정 문구들 constants로 분리
- 공통 탭 모든 값 입력 시 데이터 정상적으로 전송 확인
> [FEATURE] 공통 탭 hook-form 고도화

- src/components/common/Layout/style.ts
- layout 에서 적용된 padding 값이 하위 요소의 main 요소에 중첩되어 적용되는 문제를 수정합니다.
- 선택자 지정을 통해 layout의 자식 main에만 padding이 적용되도록 수정했어요.
> [FIX] layout main 태그가 자식 요소에 중첩되는 문제 해결

- src/components/org/OrgAdmin/AboutSection/Executives/ExecInfo.tsx
- src/components/org/OrgAdmin/AboutSection/style.ts
- src/styles/global.ts
```css
font-smooth: never;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```
description font 크기를 12 -> 14로 수정했어요
> [BUG] 폰트가 두껍게 보이는 오류 해결 및 폰트 수정

- src/components/org/OrgAdmin/CommonSection/BrandingSubColor.tsx
- src/components/org/OrgAdmin/CommonSection/ColorInputField.tsx
- src/components/org/OrgAdmin/CommonSection/style.ts
- src/components/org/OrgAdmin/CommonSection/utils.ts
1. 서브 컬러 preview랑 서브 컬러 input 정렬 맞췄습니다
2. 입력하기 편하라고 서브 컬러에 # 입력 안해도 되도록 수정했습니다
3. 서브 컬러 title, description 간격 수정했어요
> [BUG] 공통 탭 서브 컬러 input들 정렬 맞추고 컬러 코드에 # 제거하기

- src/components/org/OrgAdmin/index.tsx
- src/components/org/OrgAdmin/utils.ts
- 홈 탭에 validation을 추가합니다 
- 홈탭은 파트별 소개, 최신 소식 뿐인데, 최신 소식은 배포와 별개로 서버통신하는 애라서 파트별소개만 간단히 처리해주었습니다  
- 슬랙 드렸다시피 전 submit 작동이 안해서 (왜인지...대체..) validation handler onClick에 달아서 작동하는거 확인했습니다! 
- 한번 pull 당겨서 submit 내에서 잘 작동하는지 확인해주시면 감사드리겠습니다 🙇🏻‍♀️🙇🏻‍♀️
> [FEATURE] 홈 탭 - 파트별 소개 validation

- src/components/org/OrgAdmin/MyDropzone/index.tsx
다른 탭 갔다 와도 preview 유지 되도록 했어요
state는 언마운트 되면 사라지니까 계속해서 값이 유지될 수 있는 react hook form의 register를 이용했어요
이때 dropzone은 `image name(변수명: fileName)`과 `image file(변수명: file)` 2개를 받고 있는데 
preview로 사용되는 데이터 형식과 image file로 받고 있던 file 데이터 형식이 서로 달라서 
`새로운 변수(변수명: previewUrl)`을 추가로 저장시킨 뒤 해당 값이 있으면 useEffect를 통해 이를 불러오도록 구현했어요
https://github.com/user-attachments/assets/eaa2099a-5b0b-40ab-922f-d8d225363bf3
더 좋은 방법이 있다면 언제나 환영입니다 :)
> [BUG] 공홈 어드민 이미지 등록 했다 다른 탭 이동하면 해당 이미지 없어지는 에러 해결

- src/components/org/OrgAdmin/HomeSection/Modal.style.ts
- src/components/org/OrgAdmin/HomeSection/Modal.tsx
- src/components/org/OrgAdmin/HomeSection/NewsSection.tsx
- src/components/org/OrgAdmin/common/ActionModal/index.tsx
- src/components/org/OrgAdmin/common/ActionModal/style.ts
- src/components/org/OrgAdmin/hooks.ts
- src/components/org/OrgAdmin/index.tsx
주용이가 만든 action modal이 필요해서 따로 공통으로 빼줬어요
모든 값 입력 되어야 action modal 뜨도록 구현했습니다
완전 배포 성공하면 성공했다는 toast까지 뜨도록 했어요
하나라도 값 비워져있으면 에러 메세지 뜨는 거 다 테스트 했고 정상 작동합니다
추가로 action modal 취소하거나 배포 했을 때 checked 풀리도록 수정해줬어요
https://github.com/user-attachments/assets/f33e84ac-98eb-48b8-b79d-64e8cfcb4a96
> [FEATURE] 공홈 어드민 배포 전 모달 띄우고 성공 시 성공 alert 띄우기

- src/components/org/OrgAdmin/HomeSection/api.ts
`fetcher` 반영 및 `axios` 엔드포인트에 `config.ORG_API_URL` 반영
기존에 `news post` API를 `axios`로 보내고 있었는데, 엔드포인트에 `env production`을 적용하지 않았어서 발생하였습니다. 이는 `fetcher` 적용하면 해결되긴 하는데 `news post` 경우 `fetcher` 사용하면 자꾸 500에러 발생해서 일단 기존 `axios` 유지하되 config의 어드민 API 엔드포인트 받아와서 넣어주었어요.
> [FIX] 최신소식 추가/삭제 에러 해결

- src/components/attendanceAdmin/session/SessionList/style.ts
- src/components/org/OrgAdmin/hooks.ts
- src/components/org/OrgAdmin/index.tsx
QA할 때 매번 리로드되면 데이터 날아가고 폼 다 채워야하는게 너무 끔찍해서 제가 쓰려고 불친절한 매직버튼 만들었어요 
요구사항 없던거라 진짜 대충 만들었으니 QA 끝나면 다시 지우든 아니면 괜찮다 싶으면 좀 다듬어서 살리든 하면 될 것 같아용 
**주 기능** : 폼에 채운 데이터 임시 저장 및 복구 가능 
**기능 설명** : 
- `임시저장` : 현재 폼에 채워져있는 내용들을 로컬스토리지에 임시저장
- `불러오기` : 로컬 스토리지에 저장되어있는 폼 데이터를 불러와서 폼에 입혀요
- `이미지 채우기` : 이미지File은 로컬스토리지로 저장 및 복구가 안됩니다.(할람할이지만..) 그래서 이미지는 따로 채워주어야 하는데, 이미지만 하나하나 넣는것도 너무 귀찮은 과정이라서 첫 이미지인 소개탭배너만 넣으면, 나머지 이미지 폼(임원진 프로필, 지원하기 헤더 등등)은 다 소개탭 배너 이미지로 밀어주게 만들었어요. (다른탭 갔다오면 미리보기도 다 채워짐)
- `데이터삭제` : 로컬 스토리지 데이터를 날려줍니다 
**활용하는 법  정리** 
1. 일단 처음엔 폼 내용 다 채운다 (이미지는 다 안채워도됨. 어차피 임시저장 제대로 안됨) 
2. `임시저장` 누르기 
----- 재접속 / 리로드 -----
1. `불러오기` 누르기
2. 이미지폼은 하나하나 다시 채우거나 or 소개탭헤더만 채우고 `이미지 채우기` 버튼 누르기
3. 배포  (이미지 링크 잘못됐을 경우 알럿이 뜸. 그럼 다시 `이미지 채우기` 누르고 배포)
머지후에 이정이한테도 불친절한사용설명서 알려줄 예정입니답 (좀더 빨리만들걸)
> [FEAT] 공홈 어드민 QA용 매직버튼 만들었어요 

- src/components/bannerAdmin/BannerList/BannerList.tsx
- src/components/bannerAdmin/Header/Header.tsx
- src/pages/bannerAdmin/index.tsx
배너어드민 - 배너리스트에서 `진행 완료` 상태의 리스트의 경우 수정/삭제가 불가능하도록 수정
- 진행 완료 상태일 때 수정 / 삭제가 불가능하도록 버튼을 띄우지 않았습니다 !
이떄 아무것도 렌더링하지 않으면 테이블 레이아웃 잡아놓은 게 깨져서 Empty스타일 부여해줬습니다.
이외에도 자잘하게 테이블 정렬 & 스타일 맞춰줬습니당 !
> [FIX] 배너어드민 진행완료 배너 수정 및 삭제 비활성화

- src/components/bannerAdmin/BannerImageRegister.tsx
- src/components/bannerAdmin/BannerList/BannerList.tsx
- src/components/bannerAdmin/ContentTypeField.tsx
- src/components/bannerAdmin/CreateBannerModal.tsx
- src/components/bannerAdmin/DeleteBannerButton.tsx
- src/components/bannerAdmin/ImageDropZone.tsx
- src/components/bannerAdmin/LocationField.tsx
- src/components/bannerAdmin/PublisherField.tsx
- src/components/bannerAdmin/form/Calendar/index.tsx
- src/components/bannerAdmin/types/api.ts
- src/components/bannerAdmin/types/form.ts
- src/components/bannerAdmin/utils/getBannerStatus.ts
- src/components/bannerAdmin/utils/getBannerType.ts
- src/components/common/modal/ModalHeader/index.tsx
- src/hooks/useObserver.ts
- src/pages/_app.tsx
- src/pages/bannerAdmin/index.tsx
- src/pages/index.tsx
- src/services/api/banner/index.ts
- src/services/api/banner/query.ts
- src/types/global.d.ts
- src/utils/translator.tsx
1. 배너 삭제시 토스터 생성
2. 링크 인풋 옵셔널 인자로 변경
3. 배너 진행상황에 따른 배너 분기처리
4. 등록자 인풋 30자 제한
5. 라디오 버튼 react-hook-form Controller 로 제어
react-hook-form에서 컴포넌트를 관리하는 방법은 cotrol과 register 두개의 방법이 있어요.
```ts
<Controller
name="username"
control={control}
render={({ field }) => <input {...field} />}
/>
```
이렇게 Controller 컴포넌트를 사용하여 control 프롭으로 값을 관리하는 방법은 제어 컴포넌트를 관리할 수 있어요.
Controller는 외부 라이브러리를 사용할 때 사용하거나, 제어컴포넌트인 경우 사용해야 한다고해요.
```ts
<input {...register('username')} />
```
register로 관리를 하면 이렇게 직접적으로 등록하여 사용해줄 수 있어요. 
해당 경우 비제어로 값을 관리하게 되어 랜더링적으로 효율적이에요.
두 함수의 차이점을 잘 모르고 일단 register로 다 관리하고자 했어요. 하지만 개발자 도구를 킬때마다 `Radio` 버튼에 제어 컴포넌트를 비제어 컴포넌트로 관리해주고 있다고 경고가 떴어요. 이를 확인하고자 MDS의 `Radio` 인풋 코드를 살펴봤어요.
```ts
<input checked={checked} className={radio[size]} ref={ref} type='radio' {...props} />
```
`input` 부분만 …
> [REFACTOR] banner 생성 모달 qa (데이트피커 부분 제외)

- src/assets/icons/IcPaginationLeft.svg
- src/assets/icons/IcPaginationRight.svg
- src/assets/icons/index.ts
- src/components/bannerAdmin/BannerList/BannerList.tsx
- src/components/bannerAdmin/types/api.ts
- src/constants/index.ts
- src/pages/bannerAdmin/index.tsx
- src/services/api/banner/index.ts
- src/services/api/banner/query.ts
- src/utils/translator.tsx
배너 어드민 리스트에서 페이지네이션 기능을 추가해줬어요.
- 페이지 버튼 (ex, 1, 2, 3 ..)을 리턴해주는 함수를 작성했고, 우선은 해당 로직과 기능이 배너 어드민에서만 쓰이기 때문에 별도로 분리하지 않고 index 파일에 작성했어요.
- svg의 경우 path > stroke 색상을 바꾸는 방식으로 작성해주었어요.
- 백앤드에서 너무 친절하게도 totalPage, hasNextPage, hasPrevPage와 같은 데이터를 전달해줘서 ,, 큰 이슈는 없었어요 !
> [FEATURE] 배너 어드민 리스트 페이지네이션 적용

- src/components/common/Header/index.tsx
- src/pages/index.tsx
권한에 따라서 라우팅을 다르게 해주었어요.
MAKERS -> 알람 어드민이 초기 화면
SOPT -> 출석 어드민이 초기 화면
또 로그아웃시 세션스토리지에 토큰만 지워지고 권한값은 남아있어서 `sessionStorage.clear()' 메서드로 다 지워주도록 했어요.
> [FEATURE] 권한에 따른 라우팅 분리
